[tool.poetry]
name = "p-web-2-6"
version = "0.1.0"
description = ""
authors = ["Vasyl <gluschenkov88@gmail.com>"]
readme = "README.md"
packages = [{include = "p"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
